export interface Pais {
  nombre: string
  bandera: string
  codigo: string
}

export const PAISES: Pais[] = [
  { nombre: 'Afganistán', bandera: '🇦🇫', codigo: '+93' },
  { nombre: 'Albania', bandera: '🇦🇱', codigo: '+355' },
  { nombre: 'Alemania', bandera: '🇩🇪', codigo: '+49' },
  { nombre: 'Andorra', bandera: '🇦🇩', codigo: '+376' },
  { nombre: 'Angola', bandera: '🇦🇴', codigo: '+244' },
  { nombre: 'Anguila', bandera: '🇦🇮', codigo: '+1-264' },
  { nombre: 'Antigua y Barbuda', bandera: '🇦🇬', codigo: '+1-268' },
  { nombre: 'Arabia Saudita', bandera: '🇸🇦', codigo: '+966' },
  { nombre: 'Argelia', bandera: '🇩🇿', codigo: '+213' },
  { nombre: 'Argentina', bandera: '🇦🇷', codigo: '+54' },
  { nombre: 'Armenia', bandera: '🇦🇲', codigo: '+374' },
  { nombre: 'Aruba', bandera: '🇦🇼', codigo: '+297' },
  { nombre: 'Australia', bandera: '🇦🇺', codigo: '+61' },
  { nombre: 'Austria', bandera: '🇦🇹', codigo: '+43' },
  { nombre: 'Azerbaiyán', bandera: '🇦🇿', codigo: '+994' },
  { nombre: 'Bahamas', bandera: '🇧🇸', codigo: '+1-242' },
  { nombre: 'Bangladés', bandera: '🇧🇩', codigo: '+880' },
  { nombre: 'Barbados', bandera: '🇧🇧', codigo: '+1-246' },
  { nombre: 'Baréin', bandera: '🇧🇭', codigo: '+973' },
  { nombre: 'Bélgica', bandera: '🇧🇪', codigo: '+32' },
  { nombre: 'Belice', bandera: '🇧🇿', codigo: '+501' },
  { nombre: 'Benín', bandera: '🇧🇯', codigo: '+229' },
  { nombre: 'Bermudas', bandera: '🇧🇲', codigo: '+1-441' },
  { nombre: 'Bielorrusia', bandera: '🇧🇾', codigo: '+375' },
  { nombre: 'Bolivia', bandera: '🇧🇴', codigo: '+591' },
  { nombre: 'Bosnia y Herzegovina', bandera: '🇧🇦', codigo: '+387' },
  { nombre: 'Botsuana', bandera: '🇧🇼', codigo: '+267' },
  { nombre: 'Brasil', bandera: '🇧🇷', codigo: '+55' },
  { nombre: 'Brunéi', bandera: '🇧🇳', codigo: '+673' },
  { nombre: 'Bulgaria', bandera: '🇧🇬', codigo: '+359' },
  { nombre: 'Burkina Faso', bandera: '🇧🇫', codigo: '+226' },
  { nombre: 'Burundi', bandera: '🇧🇮', codigo: '+257' },
  { nombre: 'Bután', bandera: '🇧🇹', codigo: '+975' },
  { nombre: 'Cabo Verde', bandera: '🇨🇻', codigo: '+238' },
  { nombre: 'Camboya', bandera: '🇰🇭', codigo: '+855' },
  { nombre: 'Camerún', bandera: '🇨🇲', codigo: '+237' },
  { nombre: 'Canadá', bandera: '🇨🇦', codigo: '+1' },
  { nombre: 'Catar', bandera: '🇶🇦', codigo: '+974' },
  { nombre: 'Chad', bandera: '🇹🇩', codigo: '+235' },
  { nombre: 'Chile', bandera: '🇨🇱', codigo: '+56' },
  { nombre: 'China', bandera: '🇨🇳', codigo: '+86' },
  { nombre: 'Chipre', bandera: '🇨🇾', codigo: '+357' },
  { nombre: 'Colombia', bandera: '🇨🇴', codigo: '+57' },
  { nombre: 'Comoras', bandera: '🇰🇲', codigo: '+269' },
  { nombre: 'Congo', bandera: '🇨🇬', codigo: '+242' },
  { nombre: 'Congo (RDC)', bandera: '🇨🇩', codigo: '+243' },
  { nombre: 'Corea del Norte', bandera: '🇰🇵', codigo: '+850' },
  { nombre: 'Corea del Sur', bandera: '🇰🇷', codigo: '+82' },
  { nombre: 'Costa de Marfil', bandera: '🇨🇮', codigo: '+225' },
  { nombre: 'Costa Rica', bandera: '🇨🇷', codigo: '+506' },
  { nombre: 'Croacia', bandera: '🇭🇷', codigo: '+385' },
  { nombre: 'Cuba', bandera: '🇨🇺', codigo: '+53' },
  { nombre: 'Curazao', bandera: '🇨🇼', codigo: '+599' },
  { nombre: 'Dinamarca', bandera: '🇩🇰', codigo: '+45' },
  { nombre: 'Dominica', bandera: '🇩🇲', codigo: '+1-767' },
  { nombre: 'Ecuador', bandera: '🇪🇨', codigo: '+593' },
  { nombre: 'Egipto', bandera: '🇪🇬', codigo: '+20' },
  { nombre: 'El Salvador', bandera: '🇸🇻', codigo: '+503' },
  { nombre: 'Emiratos Árabes Unidos', bandera: '🇦🇪', codigo: '+971' },
  { nombre: 'Eritrea', bandera: '🇪🇷', codigo: '+291' },
  { nombre: 'Eslovaquia', bandera: '🇸🇰', codigo: '+421' },
  { nombre: 'Eslovenia', bandera: '🇸🇮', codigo: '+386' },
  { nombre: 'España', bandera: '🇪🇸', codigo: '+34' },
  { nombre: 'Estados Unidos', bandera: '🇺🇸', codigo: '+1' },
  { nombre: 'Estonia', bandera: '🇪🇪', codigo: '+372' },
  { nombre: 'Etiopía', bandera: '🇪🇹', codigo: '+251' },
  { nombre: 'Filipinas', bandera: '🇵🇭', codigo: '+63' },
  { nombre: 'Finlandia', bandera: '🇫🇮', codigo: '+358' },
  { nombre: 'Fiyi', bandera: '🇫🇯', codigo: '+679' },
  { nombre: 'Francia', bandera: '🇫🇷', codigo: '+33' },
  { nombre: 'Gabón', bandera: '🇬🇦', codigo: '+241' },
  { nombre: 'Gambia', bandera: '🇬🇲', codigo: '+220' },
  { nombre: 'Georgia', bandera: '🇬🇪', codigo: '+995' },
  { nombre: 'Ghana', bandera: '🇬🇭', codigo: '+233' },
  { nombre: 'Gibraltar', bandera: '🇬🇮', codigo: '+350' },
  { nombre: 'Granada', bandera: '🇬🇩', codigo: '+1-473' },
  { nombre: 'Grecia', bandera: '🇬🇷', codigo: '+30' },
  { nombre: 'Groenlandia', bandera: '🇬🇱', codigo: '+299' },
  { nombre: 'Guadalupe', bandera: '🇬🇵', codigo: '+590' },
  { nombre: 'Guam', bandera: '🇬🇺', codigo: '+1-671' },
  { nombre: 'Guatemala', bandera: '🇬🇹', codigo: '+502' },
  { nombre: 'Guayana Francesa', bandera: '🇬🇫', codigo: '+594' },
  { nombre: 'Guinea', bandera: '🇬🇳', codigo: '+224' },
  { nombre: 'Guinea-Bisáu', bandera: '🇬🇼', codigo: '+245' },
  { nombre: 'Guinea Ecuatorial', bandera: '🇬🇶', codigo: '+240' },
  { nombre: 'Guyana', bandera: '🇬🇾', codigo: '+592' },
  { nombre: 'Haití', bandera: '🇭🇹', codigo: '+509' },
  { nombre: 'Honduras', bandera: '🇭🇳', codigo: '+504' },
  { nombre: 'Hong Kong', bandera: '🇭🇰', codigo: '+852' },
  { nombre: 'Hungría', bandera: '🇭🇺', codigo: '+36' },
  { nombre: 'India', bandera: '🇮🇳', codigo: '+91' },
  { nombre: 'Indonesia', bandera: '🇮🇩', codigo: '+62' },
  { nombre: 'Irak', bandera: '🇮🇶', codigo: '+964' },
  { nombre: 'Irán', bandera: '🇮🇷', codigo: '+98' },
  { nombre: 'Irlanda', bandera: '🇮🇪', codigo: '+353' },
  { nombre: 'Isla de Man', bandera: '🇮🇲', codigo: '+44-1624' },
  { nombre: 'Islandia', bandera: '🇮🇸', codigo: '+354' },
  { nombre: 'Islas Caimán', bandera: '🇰🇾', codigo: '+1-345' },
  { nombre: 'Islas Feroe', bandera: '🇫🇴', codigo: '+298' },
  { nombre: 'Islas Marshall', bandera: '🇲🇭', codigo: '+692' },
  { nombre: 'Islas Salomón', bandera: '🇸🇧', codigo: '+677' },
  { nombre: 'Israel', bandera: '🇮🇱', codigo: '+972' },
  { nombre: 'Italia', bandera: '🇮🇹', codigo: '+39' },
  { nombre: 'Jamaica', bandera: '🇯🇲', codigo: '+1-876' },
  { nombre: 'Japón', bandera: '🇯🇵', codigo: '+81' },
  { nombre: 'Jordania', bandera: '🇯🇴', codigo: '+962' },
  { nombre: 'Kazajistán', bandera: '🇰🇿', codigo: '+7' },
  { nombre: 'Kenia', bandera: '🇰🇪', codigo: '+254' },
  { nombre: 'Kirguistán', bandera: '🇰🇬', codigo: '+996' },
  { nombre: 'Kiribati', bandera: '🇰🇮', codigo: '+686' },
  { nombre: 'Kuwait', bandera: '🇰🇼', codigo: '+965' },
  { nombre: 'Laos', bandera: '🇱🇦', codigo: '+856' },
  { nombre: 'Lesoto', bandera: '🇱🇸', codigo: '+266' },
  { nombre: 'Letonia', bandera: '🇱🇻', codigo: '+371' },
  { nombre: 'Líbano', bandera: '🇱🇧', codigo: '+961' },
  { nombre: 'Liberia', bandera: '🇱🇷', codigo: '+231' },
  { nombre: 'Libia', bandera: '🇱🇾', codigo: '+218' },
  { nombre: 'Liechtenstein', bandera: '🇱🇮', codigo: '+423' },
  { nombre: 'Lituania', bandera: '🇱🇹', codigo: '+370' },
  { nombre: 'Luxemburgo', bandera: '🇱🇺', codigo: '+352' },
  { nombre: 'Macao', bandera: '🇲🇴', codigo: '+853' },
  { nombre: 'Macedonia del Norte', bandera: '🇲🇰', codigo: '+389' },
  { nombre: 'Madagascar', bandera: '🇲🇬', codigo: '+261' },
  { nombre: 'Malasia', bandera: '🇲🇾', codigo: '+60' },
  { nombre: 'Malaui', bandera: '🇲🇼', codigo: '+265' },
  { nombre: 'Maldivas', bandera: '🇲🇻', codigo: '+960' },
  { nombre: 'Malí', bandera: '🇲🇱', codigo: '+223' },
  { nombre: 'Malta', bandera: '🇲🇹', codigo: '+356' },
  { nombre: 'Marruecos', bandera: '🇲🇦', codigo: '+212' },
  { nombre: 'Martinica', bandera: '🇲🇶', codigo: '+596' },
  { nombre: 'Mauricio', bandera: '🇲🇺', codigo: '+230' },
  { nombre: 'Mauritania', bandera: '🇲🇷', codigo: '+222' },
  { nombre: 'México', bandera: '🇲🇽', codigo: '+52' },
  { nombre: 'Micronesia', bandera: '🇫🇲', codigo: '+691' },
  { nombre: 'Moldavia', bandera: '🇲🇩', codigo: '+373' },
  { nombre: 'Mónaco', bandera: '🇲🇨', codigo: '+377' },
  { nombre: 'Mongolia', bandera: '🇲🇳', codigo: '+976' },
  { nombre: 'Montenegro', bandera: '🇲🇪', codigo: '+382' },
  { nombre: 'Mozambique', bandera: '🇲🇿', codigo: '+258' },
  { nombre: 'Myanmar', bandera: '🇲🇲', codigo: '+95' },
  { nombre: 'Namibia', bandera: '🇳🇦', codigo: '+264' },
  { nombre: 'Nauru', bandera: '🇳🇷', codigo: '+674' },
  { nombre: 'Nepal', bandera: '🇳🇵', codigo: '+977' },
  { nombre: 'Nicaragua', bandera: '🇳🇮', codigo: '+505' },
  { nombre: 'Níger', bandera: '🇳🇪', codigo: '+227' },
  { nombre: 'Nigeria', bandera: '🇳🇬', codigo: '+234' },
  { nombre: 'Noruega', bandera: '🇳🇴', codigo: '+47' },
  { nombre: 'Nueva Caledonia', bandera: '🇳🇨', codigo: '+687' },
  { nombre: 'Nueva Zelanda', bandera: '🇳🇿', codigo: '+64' },
  { nombre: 'Omán', bandera: '🇴🇲', codigo: '+968' },
  { nombre: 'Países Bajos', bandera: '🇳🇱', codigo: '+31' },
  { nombre: 'Pakistán', bandera: '🇵🇰', codigo: '+92' },
  { nombre: 'Palestina', bandera: '🇵🇸', codigo: '+970' },
  { nombre: 'Panamá', bandera: '🇵🇦', codigo: '+507' },
  { nombre: 'Papúa Nueva Guinea', bandera: '🇵🇬', codigo: '+675' },
  { nombre: 'Paraguay', bandera: '🇵🇾', codigo: '+595' },
  { nombre: 'Perú', bandera: '🇵🇪', codigo: '+51' },
  { nombre: 'Polonia', bandera: '🇵🇱', codigo: '+48' },
  { nombre: 'Portugal', bandera: '🇵🇹', codigo: '+351' },
  { nombre: 'Puerto Rico', bandera: '🇵🇷', codigo: '+1-787' },
  { nombre: 'Reino Unido', bandera: '🇬🇧', codigo: '+44' },
  { nombre: 'República Centroafricana', bandera: '🇨🇫', codigo: '+236' },
  { nombre: 'República Checa', bandera: '🇨🇿', codigo: '+420' },
  { nombre: 'República Dominicana', bandera: '🇩🇴', codigo: '+1-809' },
  { nombre: 'Reunión', bandera: '🇷🇪', codigo: '+262' },
  { nombre: 'Ruanda', bandera: '🇷🇼', codigo: '+250' },
  { nombre: 'Rumanía', bandera: '🇷🇴', codigo: '+40' },
  { nombre: 'Rusia', bandera: '🇷🇺', codigo: '+7' },
  { nombre: 'Samoa', bandera: '🇼🇸', codigo: '+685' },
  { nombre: 'San Cristóbal y Nieves', bandera: '🇰🇳', codigo: '+1-869' },
  { nombre: 'San Marino', bandera: '🇸🇲', codigo: '+378' },
  { nombre: 'San Martín', bandera: '🇸🇽', codigo: '+1-721' },
  { nombre: 'San Pedro y Miquelón', bandera: '🇵🇲', codigo: '+508' },
  { nombre: 'San Vicente y las Granadinas', bandera: '🇻🇨', codigo: '+1-784' },
  { nombre: 'Santa Lucía', bandera: '🇱🇨', codigo: '+1-758' },
  { nombre: 'Santo Tomé y Príncipe', bandera: '🇸🇹', codigo: '+239' },
  { nombre: 'Senegal', bandera: '🇸🇳', codigo: '+221' },
  { nombre: 'Serbia', bandera: '🇷🇸', codigo: '+381' },
  { nombre: 'Seychelles', bandera: '🇸🇨', codigo: '+248' },
  { nombre: 'Sierra Leona', bandera: '🇸🇱', codigo: '+232' },
  { nombre: 'Singapur', bandera: '🇸🇬', codigo: '+65' },
  { nombre: 'Siria', bandera: '🇸🇾', codigo: '+963' },
  { nombre: 'Somalia', bandera: '🇸🇴', codigo: '+252' },
  { nombre: 'Sri Lanka', bandera: '🇱🇰', codigo: '+94' },
  { nombre: 'Suazilandia', bandera: '🇸🇿', codigo: '+268' },
  { nombre: 'Sudáfrica', bandera: '🇿🇦', codigo: '+27' },
  { nombre: 'Sudán', bandera: '🇸🇩', codigo: '+249' },
  { nombre: 'Sudán del Sur', bandera: '🇸🇸', codigo: '+211' },
  { nombre: 'Suecia', bandera: '🇸🇪', codigo: '+46' },
  { nombre: 'Suiza', bandera: '🇨🇭', codigo: '+41' },
  { nombre: 'Surinam', bandera: '🇸🇷', codigo: '+597' },
  { nombre: 'Tailandia', bandera: '🇹🇭', codigo: '+66' },
  { nombre: 'Taiwán', bandera: '🇹🇼', codigo: '+886' },
  { nombre: 'Tanzania', bandera: '🇹🇿', codigo: '+255' },
  { nombre: 'Tayikistán', bandera: '🇹🇯', codigo: '+992' },
  { nombre: 'Territorio Británico del Océano Índico', bandera: '🇮🇴', codigo: '+246' },
  { nombre: 'Timor Oriental', bandera: '🇹🇱', codigo: '+670' },
  { nombre: 'Togo', bandera: '🇹🇬', codigo: '+228' },
  { nombre: 'Tonga', bandera: '🇹🇴', codigo: '+676' },
  { nombre: 'Trinidad y Tobago', bandera: '🇹🇹', codigo: '+1-868' },
  { nombre: 'Túnez', bandera: '🇹🇳', codigo: '+216' },
  { nombre: 'Turkmenistán', bandera: '🇹🇲', codigo: '+993' },
  { nombre: 'Turquía', bandera: '🇹🇷', codigo: '+90' },
  { nombre: 'Tuvalu', bandera: '🇹🇻', codigo: '+688' },
  { nombre: 'Ucrania', bandera: '🇺🇦', codigo: '+380' },
  { nombre: 'Uganda', bandera: '🇺🇬', codigo: '+256' },
  { nombre: 'Uruguay', bandera: '🇺🇾', codigo: '+598' },
  { nombre: 'Uzbekistán', bandera: '🇺🇿', codigo: '+998' },
  { nombre: 'Vanuatu', bandera: '🇻🇺', codigo: '+678' },
  { nombre: 'Vaticano', bandera: '🇻🇦', codigo: '+39' },
  { nombre: 'Venezuela', bandera: '🇻🇪', codigo: '+58' },
  { nombre: 'Vietnam', bandera: '🇻🇳', codigo: '+84' },
  { nombre: 'Yemen', bandera: '🇾🇪', codigo: '+967' },
  { nombre: 'Yibuti', bandera: '🇩🇯', codigo: '+253' },
  { nombre: 'Zambia', bandera: '🇿🇲', codigo: '+260' },
  { nombre: 'Zimbabue', bandera: '🇿🇼', codigo: '+263' },
]